name: CI
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create .mbp package
        run: |
          mkdir artifacts
          zip -9r ./artifacts/$(grep 'id:' maubot.yaml | sed 's/id: //')'-v'$(grep 'version:' maubot.yaml | sed 's/version: //').mbp inviter/* *.yaml
      - uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: ./artifacts/*.mbp
      - name: Release and attach artifacts
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
